@startuml

title VerifyLoginUser Repository
autonumber
hide footbox

participant VerifyLoginService
participant  VerifyLoginRepository #LightSeaGreen



  VerifyLoginService->  VerifyLoginRepository : VerifyUser(userbo)

     VerifyLoginRepository ->  VerifyLoginRepository : Create new instance -> DataTable as dsRecords

     VerifyLoginRepository ->  VerifyLoginRepository : Create new instance -> SqlCommand as cmd by passing ("CreateUserDetail",DBConnectionString)

    VerifyLoginRepository ->  VerifyLoginRepository : Assign cmd.command as CommandType.StoredProcedure

   VerifyLoginRepository ->  VerifyLoginRepository : Create new instance -> SqlDataAdapter as adapter
    
    alt (DBConnectionString.State == ConnectionState.Closed)
        VerifyLoginRepository ->  VerifyLoginRepository : DBConnectionString.Open()
    end

    VerifyLoginRepository -> VerifyLoginRepository : Add Parameter and send loginbo
VerifyLoginRepository -> VerifyLoginRepository : Excute.ExecuteNonQuery()


    VerifyLoginRepository -> VerifyLoginRepository : DBConnectionString.Close()

    VerifyLoginRepository-> VerifyLoginRepository: Create new instance "IsUserExist"-> Assign true if atleast one row affected
    
VerifyLoginRepository -> VerifyLoginRepository : Assign false if 0 rows affected

   VerifyLoginRepository -> VerifyLoginService: Returns IsUserExist


@enduml