@startuml

title ConfigUserData Service
autonumber

participant ConfigController
participant ConfigService #LightSeaGreen
participant ConfigRepository

alt (try)

   ConfigController -> ConfigService : GetUserData(int userid,string platform)
   ConfigService -> ConfigRepository : ConfigRepository.GetUserData(int userid,string platform)
   ConfigRepository ->ConfigService : Return ConfigBO
   ConfigService -> ConfigController : Return ServiceResult - Success (ConfigBO)


else (catch)
    ConfigService -> ConfigController : RETURN Failure Result

end


== PSEUDO CODE ==

hnote across

TRY

    ASSIGN ConfigBO configbo = ConfigRepository.GetUserData(int userid,string platform)

    **RETURN ServiceResult { status = Success, data = configbo }**

CATCH

    **RETURN ServiceResult { status = ServerError, data = null }**
    
end note

@enduml
