@startuml Controller

title VerifyUser - LoginController
autonumber
hide footbox

participant Request
participant LoginController #LightSeaGreen
participant Utilites 
participant LoginSerivce  

Request -> LoginController : verify user

alt (try block)
   LoginController -> Utilites : Validate Auth Header
    Utilites -> LoginController : returns TRUE or FALSE

    alt (Valid Header - TRUE)
        LoginController -> LoginSerivce : Call LoginServices.VerifyUser(string email,string password )
        LoginSerivce -> LoginController : return UserDetailBO 
       
        alt#Yellow #LightGreen (success : 200) 
            LoginController -> Request : Ok 200 return UserDetailBO
        else #LightGoldenRodYellow (Failure)
            LoginController -> Request : l 
        end

        note left: Uses Extension Resolver Method to return response
    else #LightGoldenRodYellow (In Valid Header - FALSE)
        LoginController -> Request : Return 401 - UnAuthorized 
    end

else #LightGoldenRodYellow (catch block)
    LoginController -> Request : Exception at Controller level - Server Error 500 return empty
end

== PSEUDO CODE ==

hnote across
HTTP Authorized GET / Verify user

TRY

    IF Auth Header is Valid THEN

        ASSIGN ServiceResult<UserDetailBO> userdetailbo = LoginSerivce.VerifyUser(string email,string password)

        ** RETURN userdetailbo.FinalResult() ** // extension resolver
    
    ELSE

        **RETURN StatusCode(401)**
        
CATCH

    SET Response Status Code = 500
    **RETURN JsonResult of new { message = e.message}**

end note

@enduml

