@startuml

title GetUserDetail Repository
autonumber
hide footbox

participant GetUserDetailService
participant GetUserDetailRepository #LightSeaGreen

alt (try)

    GetUserDetailService -> GetUserDetailRepository : GetUserDetail(userid)

   GetUserDetailRepository  -> GetUserDetailRepository  : Create new instance -> DataTable as dsRecords

   GetUserDetailRepository -> GetUserDetailRepository : Create new instance -> SqlCommand as cmd by passing ("GetUserDetail",DBConnectionString)

  GetUserDetailRepository  -> GetUserDetailRepository  : Assign cmd.command as CommandType.StoredProcedure

  GetUserDetailRepository  -> GetUserDetailRepository  : Add Parameter and pass user id

   GetUserDetailRepository  -> GetUserDetailRepository  : Create new instance -> SqlDataAdapter as adapter
    
    alt (DBConnectionString.State == ConnectionState.Closed)
       GetUserDetailRepository  -> GetUserDetailRepository  : DBConnectionString.Open()
    end

GetUserDetailRepository -> GetUserDetailRepository : execute ExecuteReader()

   GetUserDetailRepository  -> GetUserDetailRepository : adapter.Fill(dsRecords)

   GetUserDetailRepository  -> GetUserDetailRepository  : DBConnectionString.Close()

   GetUserDetailRepository  -> GetUserDetailRepository  : Create new instance -> UserDetailBO as userbo
    
  GetUserDetailRepository  -> GetUserDetailRepository  : Assign All the Values from dsRecords to userbo 

    GetUserDetailRepository -> GetUserDetailService: Returns userbo

else #LightGoldenRodYellow (catch)
    GetUserDetailRepository -> GetUserDetailService : RETURN ServiceResult - Failure
end


@enduml