@startuml

title LoginUser Service
autonumber

participant LoginController
participant LoginService #LightSeaGreen
participant LoginRepository

alt (try)

   LoginController -> LoginService : VerifyUser(string email,string password)
   LoginService -> LoginRepository : VerifyUser(string email,string password)
    LoginRepository ->LoginService : Return UserDetailBO
    LoginService -> LoginController : Return ServiceResult - Success (UserDetailBO)


else (catch)
    LoginService -> LoginController : RETURN Failure Result

end
