@startuml

title LoginUser Service
autonumber

participant LoginController
participant LoginService #LightSeaGreen
participant LoginRepository

alt (try)

   LoginController -> LoginService : VerifyUser(string email,string password)
   LoginService -> LoginRepository : LoginRepository.VerifyUser(string email,string password)
    LoginRepository ->LoginService : Return UserDetailBO
    LoginService -> LoginController : Return ServiceResult - Success (UserDetailBO)


else (catch)
    LoginService -> LoginController : RETURN Failure Result

end

== PSEUDO CODE ==

hnote across

TRY

    ASSIGN UserDetailBO userdetailbo = LoginRepository.VerifyUser(string email,string password)

    **RETURN ServiceResult { status = Success, data = userdetailbo }**

CATCH

    **RETURN ServiceResult { status = ServerError, data = null }**
    
end note
@enduml
