@startuml

title CreateUser Service
autonumber

participant SignupController
participant SignupService #LightSeaGreen
participant SignupRepository

alt (try)

   SignupController -> SingupService : CreateUser(UserDetailBO userbo)
   SignupService -> SignupRepository : Signup.CreateUser(UserDetailBO userbo)
   SignupRepository -> SignupService : Return UserDetailBO
    SignupService -> SignupController : Return ServiceResult - Success (UserDetailBO)

else (catch)
   SignupService -> SignupController : RETURN Failure Result

end

== PSEUDO CODE ==

hnote across

TRY

    ASSIGN UserDetailBO userbo = SignupRepository.CreateUser(userbo)

    **RETURN ServiceResult { status = Success, data = userbo }**

CATCH

    **RETURN ServiceResult { status = ServerError, data = null }**
    
end note

@enduml
